### ISSUE TITLE
Review current docker-compose.yml file

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/DIDocker_Hyku#9]
- [ ] Do we need these lines to initialize empty volumes/networks: https://github.com/ualbertalib/DIDocker_Hyku/blob/master/docker-compose.yml#L3-L11
- [ ] can we review if some of the port mapping/port exposing is needed? Docker compose is good at linking containers view "links" key which abstracts the ports. The rails app container can use the "links" key and be linked to postgres/redis etc. Having a nginx/apache container linking to rails. Then only one exposing port (nginx/apache port 80 which serves rails) is given to the outside world.
- [ ] review the need for app/web/setup containers (app and setup containers crash out after starting up)
- [ ] can we simply some lines, for example:
```
Redis:
    image: redis:3 (3 is the latest, but agree it’s nice to specify versions)
    command: redis-server (already the default command)
    volumes:
      - redis:/data  (already stores data inside the container...only needed if you want persistence outside of the container)
    Expose:  
      - 6379  (already does this)
    networks:
      Internal:   (this isn’t needed?)
    ports:
      - 6379:6379   (why do you want to map this to localhost? Unless you want to connect to it via your redis-cli for some reason which shouldn't be the norm)
```
- [ ] do we need to use the image from dockerhub? Does that mean we have to maintain the dockerhub image seperately. Can we build it on the fly?
